services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: x_flask2
    depends_on:
      - mariadb
    ports:
      - 80:80
    volumes:
      - .:/app

  mariadb:
    image: mariadb:10.6.20
    container_name: x_mariadb2
    environment:
      MYSQL_ROOT_PASSWORD: eksamen312luca
      MYSQL_DATABASE: x
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306

  arangodb:
    image: arangodb:latest
    container_name: arangodb2
    environment:
      - ARANGO_ROOT_PASSWORD=eksamen312luca
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3
    networks:
      - arango-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: x_phpmyadmin2
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: eksamen312luca
    ports:
      - 8080:80

volumes:
  mariadb_data:
  arango_data:

networks:
  arango-network:
    driver: bridge